{"name": "Принятие заказа с неверным ID курьера", "status": "passed", "start": 1727815912972, "stop": 1727815913391, "uuid": "b9f1f031-947f-4acd-9b19-5f47de98ad61", "historyId": "7340bb1811a392153b914aaffb7f586b", "testCaseId": "7340bb1811a392153b914aaffb7f586b", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_invalid_courier_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "POPOV"}, {"name": "thread", "value": "19208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}